name: PhysicalFighters
version: ${version}
main: physicalFighters.PhysicalFighters
api-version: '1.21'
authors: [ Xeon, Yeomryo, Ararab ]
website: https://github.com/KDY05
commands:
  va:
    description: This is a demo command.
