name: PhysicalFighters
main: physicalFighters.PhysicalFighters
version: ${version}
api-version: '1.21'
commands:
  va:
    description: This is a demo command.
  showmethemoney:
    description: This is a demo command.
