name: PhysicalFighters
version: ${version}
main: io.github.kdy05.physicalFighters.PhysicalFighters
api-version: '1.21'
authors: [ Xeon, Yeomryo, Ararab ]
website: https://github.com/KDY05
commands:
  va:
    description: main command
permissions:
  va.operate:
    description: operating permission
    default: op
