package physicalFighters.core;

import java.util.ArrayList;

import physicalFighters.abilities.*;

@SuppressWarnings("unused")
public class AbilityList {
    public static final ArrayList<Ability> AbilityList = new ArrayList<>();
    public static final Feather feather = new Feather();
    public static final Blaze blaze = new Blaze();
    public static final Shadow shadow = new Shadow();
    public static final Mirroring mirroring = new Mirroring();
    public static final ReverseAlchemy reversealchemy = new ReverseAlchemy();
    public static final Blind blind = new Blind();
    public static final Anorexia anorexia = new Anorexia();
    public static final Jumper jumper = new Jumper();
    public static final Medic medic = new Medic();
    public static final Lockdown lockdown = new Lockdown();
    public static final Time time = new Time();
    public static final NuclearPunch nuclearpunch = new NuclearPunch();
    public static final Bishop bishop = new Bishop();
    public static final Phoenix phoenix = new Phoenix();
    public static final Berserker berserker = new Berserker();
    public static final Archer archer = new Archer();
    public static final Aegis aegis = new Aegis();
    public static final Clocking clocking = new Clocking();
    public static final MachineGun machinegun = new MachineGun();
    public static final ShockWave shockwave = new ShockWave();
    public static final Thor thor = new Thor();
    public static final Assimilation assimilation = new Assimilation();
    public static final Demigod demigod = new Demigod();
    public static final Apollon apolln = new Apollon();
    public static final Slower slower = new Slower();
    public static final Luffy luffy = new Luffy();
    public static final Zombie zombie = new Zombie();
    public static final Poison poison = new Poison();
    public static final Ace ace = new Ace();
    public static final Flower flower = new Flower();
    public static final CP9 cp9 = new CP9();
    public static final Poseidon poseidon = new Poseidon();
    public static final Akainu akainu = new Akainu();
    public static final Explosion explosion = new Explosion();
    public static final Trash trash = new Trash();
    public static final Guard guard = new Guard();
    public static final Sasuke sasuke = new Sasuke();
    public static final Ckyomi ckyomi = new Ckyomi();
    public static final PoisonArrow poisonArrow = new PoisonArrow();
    public static final FallArrow fallArrow = new FallArrow();
    public static final Gaara gaara = new Gaara();
    public static final Roclee roclee = new Roclee();
    public static final Minato minato = new Minato();
    public static final Tranceball tranceball = new Tranceball();
    public static final Kimimaro kimimaro = new Kimimaro();
    public static final Pagi pagi = new Pagi();
    public static final Amateras amateras = new Amateras();
    public static final Aokizi aokizi = new Aokizi();
    public static final Gladiator gladiator = new Gladiator();
    public static final Time2 time2 = new Time2();
    public static final Zoro zoro = new Zoro();
    public static final Fish fish = new Fish();
    public static final Kaiji kaiji = new Kaiji();
    public static final Kijaru kijaru = new Kijaru();
    public static final Cuma cuma = new Cuma();
    public static final Enel enel = new Enel();
    public static final Blitzcrank blitzcrank = new Blitzcrank();
    public static final Fireball fireball = new Fireball();
    public static final Booster booster = new Booster();
    public static final Crocodile crocodile = new Crocodile();
    public static final Temari Temari = new Temari();
    public static final Trap trap = new Trap();
    public static final Multishot Multishot = new Multishot();
    public static final SuperFan SuperFan = new SuperFan();
    public static final Killtolevelup Killtolevelup = new Killtolevelup();
    public static final Fallingarrow Fallingarrow = new Fallingarrow();
    public static final Nonuck Nonuck = new Nonuck();
    public static final Hulk Hulk = new Hulk();
    public static final Assassin Assassin = new Assassin();
    public static final Boom Boom = new Boom();
    public static final Devil Devil = new Devil();
    public static final Angel Angel = new Angel();
    public static final Fittingroom Fittingroom = new Fittingroom();
    public static final Fly Fly = new Fly();
    public static final Teleporter Teleporter = new Teleporter();
    public static final Magnet Magnet = new Magnet();
    public static final Pressure Pressure = new Pressure();
    public static final ExplosionPa Flamethrower = new ExplosionPa();
    public static final Ninja Ninja = new Ninja();
    public static final Uppercut Uppercut = new Uppercut();
    public static final GravityBoots GravityBoots = new GravityBoots();
    public static final Infighter Infighter = new Infighter();
    public static final Sunbi Sunbi = new Sunbi();
    public static final Ahri Ahri = new Ahri();
    public static final ExplosionGlove ExplosionGlove = new ExplosionGlove();
    public static final Nasus Nasus = new Nasus();
    public static final Issac issac = new Issac();
    public static final Thunder Thunder = new Thunder();
    public static final Poksi poksi = new Poksi();
    public static final Tracer Tracer = new Tracer();
    public static final Genji Genji = new Genji();
    public static final Paladin Paladin = new Paladin();
    public static final TwistedFate TwistedFate = new TwistedFate();
    public static final gongban gongban = new gongban();
    public static Yeomryo yeomryo;
}
